name: documentation
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/docs.yml"
      - "docs/conf.py"
      - "docs/index.rst"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root
    steps:
      - name: Install make, TeX Live and Sphinx
        run: |
          sudo apt-get update
          # install this first to avoid user interaction in install
          sudo apt-get install -y tzdata
          sudo apt-get install -y make
          sudo apt-get install -y texlive
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-luatex
          sudo apt-get install -y latexmk
          sudo apt-get install -y fonts-freefont-otf
          sudo apt-get install -y xindy
          sudo apt-get install -y python3-sphinx
          sage -pip install sphinx-book-theme
      - name: Checkout QuiverTools
        uses: actions/checkout@v4
      - name: Install QuiverTools
        run: sage --pip install .
      - name: Run Sphinx
        run: |
          cd docs
          make html
          make latexpdf
      - name: Make sure CNAME is there
        run:
          echo "sage.quiver.tools" > docs/_build/html/CNAME
      - name: Create artifact
        run: |
          mkdir -p github-artifacts/docs
          mv docs/_build/latex/quivertools.pdf ./github-artifacts/documentation.pdf
          mv docs/_build/html/* ./github-artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./github-artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github-artifacts
      - name: Move docs
        run: mkdir -p github-deploy && mv github-artifacts/*/* github-deploy
      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github-deploy
          publish_branch: docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
