name: Unit tests
on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root
    steps:
      - name: Install make and Sphinx
        run: |
          sudo apt-get install -y make
          sudo apt-get install -y python3-sphinx
      - name: Checkout QuiverTools
        uses: actions/checkout@v3
      - name: Install QuiverTools
        run: sage --pip install .
      - name: Run the tests
        run: |
          sage -t quiver/quiver.py
          sage -t quiver/moduli.py
